"""Wire-level helpers for the model-free DeskBot voice sidecar.

The sidecar deliberately keeps this module independent of ASR/TTS model
implementations.  A real worker can replace the fake transcriber/synthesizer
while retaining the request and response envelopes consumed by Node.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import json
import re
import unicodedata
import uuid
from dataclasses import dataclass
from typing import Any, Mapping


SCHEMA_VERSION = "voice.sidecar.v0.1"
ERROR_SCHEMA = "voice.error.v0.1"
ASR_SCHEMA = "voice.asr-result.v0.1"
TTS_SCHEMA = "voice.tts-result.v0.1"
CANCEL_SCHEMA = "voice.cancel.v0.1"
SERVICE_NAME = "voice-sidecar"
SERVICE_VERSION = "0.1.0"

MAX_TEXT_LENGTH = 32_000
MAX_PROFILE_LENGTH = 256
MAX_AUDIO_BYTES = 12 * 1024 * 1024

ASR_STAGES = ("partial", "final")
SUPPORTED_CAPTURE_CODECS = ("pcm_s16le", "wav", "g711a")
SUPPORTED_TTS_CODECS = ("wav", "pcm_s16le")
SUPPORTED_SAMPLE_RATES = (8_000, 16_000, 24_000)
DEFAULT_SAMPLE_RATE_HZ = 16_000
DEFAULT_CHANNELS = 1
DEFAULT_TTS_PROFILE = "shaping-neutral"
# ``ember`` remains a compatibility alias for archived requests; new callers
# should use the canonical 聚形域 profile.
KNOWN_TTS_PROFILES = ("shaping-neutral", "default", "neutral", "ember")


class ProtocolError(Exception):
    """An expected request/protocol failure with a stable machine code."""

    def __init__(
        self,
        status: int,
        code: str,
        message: str,
        *,
        details: Any = None,
        request_id: str | None = None,
        correlation_id: str | None = None,
    ) -> None:
        super().__init__(message)
        self.status = status
        self.code = code
        self.message = message
        self.details = details
        self.request_id = request_id
        self.correlation_id = correlation_id


def new_id(prefix: str) -> str:
    """Return a log-safe opaque ID.

    UUIDs are generated by the sidecar only for convenience; callers should
    provide stable IDs when retry/idempotency semantics matter.
    """

    return f"{prefix}-{uuid.uuid4()}"


def _as_object(value: Any, field: str = "body") -> dict[str, Any]:
    if not isinstance(value, Mapping) or isinstance(value, (str, bytes, bytearray)):
        raise ProtocolError(400, "invalid_request", f"{field} must be a JSON object")
    return dict(value)


def _text(value: Any, field: str, *, required: bool = True, max_length: int = MAX_TEXT_LENGTH) -> str | None:
    if value is None and not required:
        return None
    if not isinstance(value, str):
        raise ProtocolError(400, "invalid_request", f"{field} must be a string")
    if value.strip() == "":
        if required:
            raise ProtocolError(400, "invalid_request", f"{field} must be a non-empty string")
        return None
    if len(value) > max_length:
        raise ProtocolError(413, "text_too_large", f"{field} exceeds {max_length} characters")
    return value


def request_identity(body: Mapping[str, Any]) -> tuple[str, str]:
    """Normalize request/correlation IDs.

    Missing IDs are generated at the sidecar boundary.  This makes direct
    smoke tests ergonomic while preserving a correlation value in every
    downstream event.  Node should normally provide both values explicitly.
    """

    request_id = (
        new_id("req")
        if "request_id" not in body or body.get("request_id") is None
        else _text(body.get("request_id"), "request_id", max_length=128)
    )
    correlation_id = (
        new_id("corr")
        if "correlation_id" not in body or body.get("correlation_id") is None
        else _text(body.get("correlation_id"), "correlation_id", max_length=128)
    )
    return request_id.strip(), correlation_id.strip()


def optional_identity(body: Mapping[str, Any]) -> tuple[str | None, str | None]:
    """Extract IDs for error responses without generating new values."""

    request_id = body.get("request_id", body.get("job_id"))
    correlation_id = body.get("correlation_id")
    return (
        request_id.strip() if isinstance(request_id, str) and request_id.strip() else None,
        correlation_id.strip() if isinstance(correlation_id, str) and correlation_id.strip() else None,
    )


def error_body(error: ProtocolError, *, request_id: str | None = None, correlation_id: str | None = None) -> dict[str, Any]:
    """Build the only error envelope emitted by the HTTP service."""

    body: dict[str, Any] = {
        "schema": ERROR_SCHEMA,
        "ok": False,
        "request_id": request_id if request_id is not None else error.request_id,
        "correlation_id": correlation_id if correlation_id is not None else error.correlation_id,
        "error": {"code": error.code, "message": error.message},
    }
    if error.details is not None:
        body["error"]["details"] = error.details
    return body


def success_base(schema: str, *, request_id: str, correlation_id: str) -> dict[str, Any]:
    return {
        "schema": schema,
        "ok": True,
        "request_id": request_id,
        "correlation_id": correlation_id,
    }


def clean_utterance(raw_utterance: str) -> str:
    """Apply conservative, deterministic text cleanup.

    This is intentionally not a semantic rewriter.  It normalizes Unicode
    compatibility forms, removes zero-width markers, and collapses whitespace
    so that the raw model output remains auditable beside the text sent to
    Node/DeepSeek.
    """

    normalized = unicodedata.normalize("NFKC", raw_utterance)
    normalized = normalized.replace("\u200b", "").replace("\ufeff", "")
    return re.sub(r"\s+", " ", normalized).strip()


def _decode_audio(value: Any) -> bytes:
    if isinstance(value, Mapping):
        value = (
            value.get("base64")
            or value.get("data")
            or value.get("data_base64")
            or value.get("audio_base64")
        )
    if not isinstance(value, str) or value == "":
        raise ProtocolError(400, "invalid_audio", "audio_b64 must be a non-empty base64 string")
    try:
        payload = base64.b64decode(value, validate=True)
    except (ValueError, TypeError, binascii.Error):
        raise ProtocolError(400, "invalid_audio", "audio_b64 is not valid base64") from None
    if not payload:
        raise ProtocolError(400, "invalid_audio", "audio payload must not be empty")
    if len(payload) > MAX_AUDIO_BYTES:
        raise ProtocolError(413, "audio_too_large", f"audio payload exceeds {MAX_AUDIO_BYTES} bytes")
    return payload


def normalize_audio_format(
    value: Any,
    *,
    direction: str,
    default_codec: str,
) -> dict[str, Any]:
    """Validate and canonicalize a capture/playback format descriptor."""

    if value is None:
        value = {}
    if isinstance(value, str):
        value = {"codec": value}
    if not isinstance(value, Mapping):
        raise ProtocolError(400, "invalid_audio_format", "format must be a string or object")
    raw_codec = value.get("codec", value.get("encoding", default_codec))
    if not isinstance(raw_codec, str) or raw_codec.strip() == "":
        raise ProtocolError(400, "invalid_audio_format", "format.codec must be a non-empty string")
    codec = raw_codec.strip().lower()
    allowed = SUPPORTED_CAPTURE_CODECS if direction == "capture" else SUPPORTED_TTS_CODECS
    if codec not in allowed:
        raise ProtocolError(
            422,
            "unsupported_audio_format",
            f"{direction} codec {codec!r} is not supported by the fake sidecar",
            details={"direction": direction, "supported_codecs": list(allowed)},
        )
    if codec == "g711a" and direction == "capture" and value.get("sample_rate_hz", 8_000) != 8_000:
        raise ProtocolError(
            422,
            "unsupported_audio_format",
            "g711a capture requires an 8000 Hz sample rate",
            details={"codec": codec, "required_sample_rate_hz": 8_000},
        )
    default_sample_rate = 8_000 if codec == "g711a" and direction == "capture" else DEFAULT_SAMPLE_RATE_HZ
    raw_sample_rate = value.get("sample_rate_hz", default_sample_rate)
    raw_channels = value.get("channels", DEFAULT_CHANNELS)
    if (
        isinstance(raw_sample_rate, bool)
        or isinstance(raw_channels, bool)
        or not isinstance(raw_sample_rate, int)
        or not isinstance(raw_channels, int)
    ):
        raise ProtocolError(400, "invalid_audio_format", "sample_rate_hz and channels must be integers")
    sample_rate = raw_sample_rate
    channels = raw_channels
    if sample_rate not in SUPPORTED_SAMPLE_RATES:
        raise ProtocolError(
            422,
            "unsupported_audio_format",
            f"sample rate {sample_rate} Hz is not supported",
            details={"supported_sample_rates_hz": list(SUPPORTED_SAMPLE_RATES)},
        )
    if channels != 1:
        raise ProtocolError(422, "unsupported_audio_format", "only mono audio is supported", details={"channels": [1]})
    return {"codec": codec, "sample_rate_hz": sample_rate, "channels": channels}


def audio_metadata(payload: bytes, fmt: Mapping[str, Any], *, mime_type: str, duration_ms: int | None = None) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "format": dict(fmt),
        "mime_type": mime_type,
        "encoding": "base64",
        "byte_count": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
    }
    if duration_ms is not None:
        metadata["duration_ms"] = duration_ms
    return metadata


def asr_input(body: Mapping[str, Any]) -> dict[str, Any]:
    """Validate an ASR request and return normalized internal fields."""

    body = _as_object(body)
    request_id, correlation_id = request_identity(body)
    stage_value = body.get("stage")
    if stage_value is None:
        stage_value = "partial" if body.get("partial") is True else "final"
    if not isinstance(stage_value, str):
        raise ProtocolError(400, "invalid_stage", "stage must be partial or final", request_id=request_id, correlation_id=correlation_id)
    stage = stage_value.strip().lower()
    if stage not in ASR_STAGES:
        raise ProtocolError(400, "invalid_stage", "stage must be partial or final", details={"allowed": list(ASR_STAGES)}, request_id=request_id, correlation_id=correlation_id)

    audio_bytes: bytes | None = None
    audio_value = body.get("audio_b64", body.get("audio_base64"))
    if audio_value is None and isinstance(body.get("audio"), (str, Mapping)):
        audio_value = body.get("audio")
    if audio_value is not None:
        audio_bytes = _decode_audio(audio_value)
    raw = body.get("raw_utterance", body.get("raw_text"))
    if raw is None or (isinstance(raw, str) and raw.strip() == "" and audio_bytes is not None):
        raw = body.get("text", body.get("text_hint", body.get("fake_text")))
    if raw is None:
        if audio_bytes is None:
            raise ProtocolError(400, "missing_input", "provide text/raw_utterance or audio_b64", request_id=request_id, correlation_id=correlation_id)
        # Model-free mode cannot decode speech.  A digest marker makes this
        # limitation explicit and deterministic without pretending to be ASR.
        raw = f"[fake-audio:{hashlib.sha256(audio_bytes).hexdigest()[:12]}]"
    raw = _text(raw, "raw_utterance", max_length=MAX_TEXT_LENGTH)
    supplied_clean = body.get("clean_utterance", body.get("cleaned_text"))
    if supplied_clean is not None:
        supplied_clean = _text(supplied_clean, "clean_utterance", max_length=MAX_TEXT_LENGTH)
        cleaned = clean_utterance(supplied_clean)
    else:
        cleaned = clean_utterance(raw)

    confidence = body.get("confidence")
    if confidence is None:
        confidence = 0.55 if stage == "partial" else 0.9
    if isinstance(confidence, bool):
        raise ProtocolError(400, "invalid_confidence", "confidence must be a number", request_id=request_id, correlation_id=correlation_id)
    try:
        confidence = float(confidence)
    except (TypeError, ValueError):
        raise ProtocolError(400, "invalid_confidence", "confidence must be a number", request_id=request_id, correlation_id=correlation_id) from None
    if not 0.0 <= confidence <= 1.0:
        raise ProtocolError(400, "invalid_confidence", "confidence must be between 0 and 1", request_id=request_id, correlation_id=correlation_id)

    utterance_id = _text(body.get("utterance_id") or body.get("stream_id"), "utterance_id", required=False, max_length=128) or new_id("utt")
    stream_id = _text(body.get("stream_id") or utterance_id, "stream_id", required=False, max_length=128) or utterance_id
    event_id = _text(body.get("event_id"), "event_id", required=False, max_length=128) or f"asr-{request_id}-{stage}"
    format_value = body.get("audio_format", body.get("format"))
    if format_value is None and isinstance(audio_value, Mapping):
        format_value = audio_value.get("format", audio_value)
    fmt = normalize_audio_format(format_value, direction="capture", default_codec="pcm_s16le")
    audio = None
    if audio_bytes is not None:
        if fmt["codec"] == "pcm_s16le" and len(audio_bytes) % 2:
            raise ProtocolError(
                400,
                "invalid_audio",
                "pcm_s16le payload must contain complete 16-bit samples",
                request_id=request_id,
                correlation_id=correlation_id,
            )
        audio = audio_metadata(
            audio_bytes,
            fmt,
            mime_type="audio/wav" if fmt["codec"] == "wav" else "application/octet-stream",
        )
        audio["input"] = True
    return {
        "request_id": request_id,
        "correlation_id": correlation_id,
        "stage": stage,
        "is_final": stage == "final",
        "utterance_id": utterance_id,
        "stream_id": stream_id,
        "event_id": event_id,
        "raw_utterance": raw,
        "clean_utterance": cleaned,
        "confidence": confidence,
        "language": _text(body.get("language"), "language", required=False, max_length=32) or "und",
        "character_id": _text(body.get("character_id"), "character_id", required=False, max_length=128),
        "device_id": _text(body.get("device_id"), "device_id", required=False, max_length=128),
        "shell_id": _text(body.get("shell_id"), "shell_id", required=False, max_length=128),
        "role_revision": body.get("role_revision"),
        "metadata": dict(body["metadata"]) if isinstance(body.get("metadata"), Mapping) else None,
        "format": fmt,
        "audio": audio,
    }


def tts_input(body: Mapping[str, Any]) -> dict[str, Any]:
    """Validate a TTS request and return normalized internal fields."""

    body = _as_object(body)
    request_id, correlation_id = request_identity(body)
    text = body.get("text") or body.get("clean_utterance")
    text = _text(text, "text", max_length=MAX_TEXT_LENGTH)
    profile_value = body.get("profile") or body.get("voice_profile") or body.get("profile_id") or DEFAULT_TTS_PROFILE
    if isinstance(profile_value, str):
        profile = profile_value.strip()
        if not profile:
            raise ProtocolError(400, "invalid_profile", "profile must not be empty", request_id=request_id, correlation_id=correlation_id)
        if len(profile) > MAX_PROFILE_LENGTH:
            raise ProtocolError(413, "profile_too_large", "profile exceeds 256 characters", request_id=request_id, correlation_id=correlation_id)
        profile_payload: str | dict[str, Any] = profile
    elif isinstance(profile_value, Mapping):
        profile_payload = dict(profile_value)
        if len(json.dumps(profile_payload, ensure_ascii=False)) > MAX_PROFILE_LENGTH:
            raise ProtocolError(413, "profile_too_large", "profile exceeds 256 characters", request_id=request_id, correlation_id=correlation_id)
        profile_name = profile_payload.get(
            "name",
            profile_payload.get("id", profile_payload.get("profile_id", DEFAULT_TTS_PROFILE)),
        )
        if not isinstance(profile_name, str) or not profile_name.strip():
            raise ProtocolError(400, "invalid_profile", "profile.name must be a non-empty string", request_id=request_id, correlation_id=correlation_id)
        profile_payload["name"] = profile_name.strip()
        # Keep the client-facing profile identifier when one was supplied.
        if "profile_id" in profile_payload and not isinstance(profile_payload["profile_id"], str):
            raise ProtocolError(400, "invalid_profile", "profile.profile_id must be a string", request_id=request_id, correlation_id=correlation_id)
    else:
        raise ProtocolError(400, "invalid_profile", "profile must be a string or object", request_id=request_id, correlation_id=correlation_id)

    fmt = normalize_audio_format(body.get("format", body.get("audio_format")), direction="playback", default_codec="wav")
    stream_id = _text(body.get("stream_id"), "stream_id", required=False, max_length=128) or new_id("tts")
    return {
        "request_id": request_id,
        "correlation_id": correlation_id,
        "text": text,
        "profile": profile_payload,
        "format": fmt,
        "stream_id": stream_id,
        "character_id": _text(body.get("character_id"), "character_id", required=False, max_length=128),
        "device_id": _text(body.get("device_id"), "device_id", required=False, max_length=128),
        "shell_id": _text(body.get("shell_id"), "shell_id", required=False, max_length=128),
        "role_revision": body.get("role_revision"),
        "metadata": dict(body["metadata"]) if isinstance(body.get("metadata"), Mapping) else None,
    }


def make_asr_event(fields: Mapping[str, Any], *, occurred_at: str) -> dict[str, Any]:
    """Create the event Node can submit to ``/api/event``."""

    payload: dict[str, Any] = {
        "stage": fields["stage"],
        "text": fields["clean_utterance"],
        "raw_utterance": fields["raw_utterance"],
        "clean_utterance": fields["clean_utterance"],
        "confidence": fields["confidence"],
        "language": fields["language"],
        "utterance_id": fields["utterance_id"],
        "stream_id": fields["stream_id"],
    }
    if fields.get("audio") is not None:
        payload["audio"] = fields["audio"]
    if fields.get("metadata") is not None:
        payload["metadata"] = fields["metadata"]
    return {
        "schema": "foundry.event.v0.1",
        "event_id": fields["event_id"],
        "type": f"voice.asr.{fields['stage']}",
        "source": "voice-sidecar",
        "occurred_at": occurred_at,
        "character_id": fields.get("character_id"),
        "device_id": fields.get("device_id"),
        "shell_id": fields.get("shell_id"),
        "role_revision": fields.get("role_revision"),
        "correlation_id": fields["correlation_id"],
        "payload": payload,
    }


def profile_name(profile: str | Mapping[str, Any]) -> str:
    if isinstance(profile, str):
        return profile
    return str(profile.get("name", DEFAULT_TTS_PROFILE))


@dataclass(frozen=True)
class Capabilities:
    """Static capabilities advertised by the baseline worker."""

    asr: bool = True
    tts: bool = True

    def as_dict(self) -> dict[str, Any]:
        capture_formats = [
            {"codec": "pcm_s16le", "sample_rate_hz": 16_000, "channels": 1},
            *[
                {"codec": "pcm_s16le", "sample_rate_hz": rate, "channels": 1}
                for rate in SUPPORTED_SAMPLE_RATES
                if rate != 16_000
            ],
            *[
                {"codec": "wav", "sample_rate_hz": rate, "channels": 1}
                for rate in SUPPORTED_SAMPLE_RATES
            ],
            {"codec": "g711a", "sample_rate_hz": 8_000, "channels": 1},
        ]
        playback_formats = [
            {"codec": "wav", "sample_rate_hz": 16_000, "channels": 1},
            *[
                {"codec": "wav", "sample_rate_hz": rate, "channels": 1}
                for rate in SUPPORTED_SAMPLE_RATES
                if rate != 16_000
            ],
            *[
                {"codec": "pcm_s16le", "sample_rate_hz": rate, "channels": 1}
                for rate in SUPPORTED_SAMPLE_RATES
            ],
        ]
        return {
            "asr": {
                "available": self.asr,
                "mode": "fake",
                "streaming": True,
                "stages": list(ASR_STAGES),
                "input_codecs": list(SUPPORTED_CAPTURE_CODECS),
                "formats": capture_formats,
                "sample_rates_hz": list(SUPPORTED_SAMPLE_RATES),
                "channels": [1],
                "languages": ["und"],
            },
            "tts": {
                "available": self.tts,
                "mode": "fake",
                "streaming": False,
                "output_codecs": list(SUPPORTED_TTS_CODECS),
                "formats": playback_formats,
                "sample_rates_hz": list(SUPPORTED_SAMPLE_RATES),
                "channels": [1],
                "profiles": list(KNOWN_TTS_PROFILES),
            },
            "cancellation": {"supported": True, "scope": ["request_id", "correlation_id"]},
            "timeouts": {"supported": True, "unit": "ms", "max_ms": 120_000},
            # Firmware/bridge adapters commonly look for these names when
            # selecting a format during their hello negotiation.
            "audio": {
                "capture_formats": capture_formats,
                "playback_formats": playback_formats,
            },
        }
